# Generated by Django 4.2.7 on 2023-12-04 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_airport_alter_ticket_destination_alter_ticket_origin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='passenger',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Cost',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='origin',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField(max_length=100)),
                ('cost', models.IntegerField(default=0, max_length=100000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_destination', to='airport.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_origin', to='airport.airport')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport.flight'),
            preserve_default=False,
        ),
    ]
