# Generated by Django 4.2.7 on 2023-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_ticket_passenger_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
