# Generated by Django 4.2.7 on 2023-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
