# Generated by Django 4.2.7 on 2023-12-07 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_ticket_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store_type', models.CharField(max_length=255)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=255)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='airport.airport')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='airport.store')),
            ],
        ),
    ]
