# Generated by Django 4.2.7 on 2023-12-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_flightcompany_store_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aircarft_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airport.aircraft'),
            preserve_default=False,
        ),
    ]
