# Generated by Django 4.2.7 on 2023-12-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0010_airline_flight_air_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(default=1, upload_to='air_craft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightcompany',
            name='image',
            field=models.ImageField(default=1, upload_to='companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default=1, upload_to='workers'),
            preserve_default=False,
        ),
    ]
