# Generated by Django 4.2.7 on 2023-12-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0011_aircraft_image_flightcompany_image_worker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='airport.flightcompany'),
            preserve_default=False,
        ),
    ]
