# Generated by Django 4.2.7 on 2023-12-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0012_airport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
